version: "3"
services:
  rails:
    build: .
    env_file:
      - .env
    command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]
    volumes:
      - .:/app
    networks:
      - rails
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_AUTH_METHOD: trust
    networks:
      - rails
    ports:
      - "5432:5432"
networks:
  rails:
    driver: "bridge"
